medicine_service:
  ip: 0.0.0.0
  port: 50001

medicine_api:
  ip: 0.0.0.0
  port: 8080

pagination:
  pn: 1
  ps: 10

log:
  file_path: "./log/log-info.log"
  max_size: 1
  max_backups: 3
  max_age: 30

allow_origins:
  - http://localhost:5173
  - http://localhost:3000
